repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        additional_dependencies: [types-all]
        entry: poetry run mypy
        args: [--config-file=pyproject.toml]
        files: src/
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies: [pyproject-flake8]
        entry: poetry run pflake8
        args: [--config=pyproject.toml]
        files: src/
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.4.2
    hooks:
      - id: black
        entry: poetry run black
        args: [--config=pyproject.toml]
        files: src/
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        entry: poetry run isort
        args: [--settings-path=pyproject.toml]
        files: src/
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        entry: poetry run autoflake
        args: [--config=pyproject.toml]
        files: src/
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.8
    hooks:
      - id: bandit
        additional_dependencies: ["bandit[toml]"]
        entry: poetry run bandit
        args: ["-c", "pyproject.toml", "-r"]
        files: src/
