name: Generate Coverage Badge
description: Generate a code coverage badge for the project

inputs:
  image_name:
    description: The Docker image to use to generate the coverage badge
    required: true
  image_tag:
    description: The tag for the Docker image to use to generate the coverage badge
    required: true
  volume_name:
    description: The name of the Docker volume where coverage reports are mounted
    required: true
  mount_path:
    description: The path inside the Docker container where the coverage reports are mounted
    required: true
  output_path:
    description: The path where the coverage badge will be saved in the host
    required: true

outputs:
  output_path:
    description: The path where the coverage badge will be saved in the host
    value: ${{ inputs.output_path }}

runs:
  using: composite
  steps:
    - name: Generate Coverage Badge
      id: generate_coverage_badge
      run: docker run -v ${{ inputs.volume_name }}:${{ inputs.mount_path }} --rm ${{ inputs.image_name }}:${{ inputs.image_tag }} /bin/bash -c "cd ${{ inputs.mount_path }} && poetry run coverage-badge -o ${{ inputs.output_mount }}/coverage.svg"
      shell: bash

    - name: Generate HTML Coverage Report
      id: generate_html_coverage_report
      run: docker run -v ${{ inputs.volume_name }}:${{ inputs.mount_path }} --rm ${{ inputs.image_name }}:${{ inputs.image_tag }} poetry run coverage html --data-file=${{ inputs.mount_path }}/.coverage -d ${{ inputs.mount_path }}
      shell: bash

    - name: Copy Coverage Badge
      id: copy_coverage_badge
      run: docker cp $(docker create -v ${{ inputs.volume_name }}:${{ inputs.mount_path }} --name tmp_container ${{ inputs.image_name }}:${{ inputs.image_tag }}):${{ inputs.mount_path }} ${{ inputs.output_path }} ; docker rm tmp_container
      shell: bash
